import Head from "next/head";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";
import Link from "next/link";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const projects = fs.readdirSync(`${__dirname}/(projects)`);

const projectNames = projects.filter((project) =>
  fs.statSync(`${__dirname}/(projects)/${project}`).isDirectory()
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] pt-10">
        <h1 className="text-lg text-white">Particle Playground!</h1>

        <h2 className="text-lg text-white">Projects</h2>
        {projectNames.map((projectName) => (
          <Link
            key={projectName}
            href={`/${projectName}`}
            className="text-white underline"
          >
            {projectName}
          </Link>
        ))}
      </main>
    </>
  );
}
